name: CI/CD Pipeline

on:
  push:
    branches-ignore:
      - documents # Exclude pushes to the "documents" branch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: self-hosted # Use Windows runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: Code/Frontend/package-lock.json # Ensure correct caching

      - name: Install Dependencies
        working-directory: ./Code/Frontend
        run: npm i

      - name: Build the Project
        working-directory: ./Code/Frontend
        run: npm run build

      - name: Run Unit Tests
        working-directory: ./Code/Frontend
        run: npm run test:unit

  docker-build-and-push:
    needs: build-and-test
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Display debugging information
      - name: Debug Info
        shell: pwsh
        run: |
          Write-Host "GitHub Repository: ${{ github.repository }}"
          Write-Host "Image Name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          Write-Host "Actor: ${{ github.actor }}"

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      # Enhanced extraction of image digest with strict formatting
      - name: Extract image digest
        id: digest
        shell: pwsh
        run: |
          # First, attempt to get digest directly from docker build-push-action
          $buildDigest = "${{ steps.build-and-push.outputs.digest }}"
          
          if ($buildDigest -and $buildDigest -match '^sha256:[a-f0-9]{64}$') {
            Write-Host "✅ Valid digest from build output: $buildDigest"
            echo "IMAGE_DIGEST=$buildDigest" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "⚠️ No valid digest from build output, pulling image to extract digest"
            
            # Normalize image name for docker operations
            $imageName = "${{ env.REGISTRY }}/${{ github.repository }}".ToLower()
            $imageWithTag = "${imageName}:latest"
            
            # Pull the image to ensure it's available locally
            docker pull $imageWithTag
            
            # Attempt multiple ways to get the digest
            try {
              # Method 1: Direct inspection of RepoDigests
              $repoDigests = docker inspect $imageWithTag --format='{{json .RepoDigests}}' | ConvertFrom-Json
              
              if ($repoDigests -and $repoDigests.Count -gt 0) {
                # Extract just the digest part (after @)
                foreach ($rd in $repoDigests) {
                  if ($rd -match '@(sha256:[a-f0-9]{64})$') {
                    $extractedDigest = $Matches[1]
                    Write-Host "✅ Found valid digest from RepoDigests: $extractedDigest"
                    echo "IMAGE_DIGEST=$extractedDigest" >> $env:GITHUB_OUTPUT
                    break
                  }
                }
              }
              
              # If we still don't have a valid digest, try another method
              if (-not (Test-Path env:GITHUB_OUTPUT) -or -not (Get-Content $env:GITHUB_OUTPUT | Select-String "IMAGE_DIGEST=")) {
                # Method 2: Using docker manifest inspect
                $manifest = docker manifest inspect $imageWithTag
                if ($manifest -match '"digest":\s*"(sha256:[a-f0-9]{64})"') {
                  $manifestDigest = $Matches[1]
                  Write-Host "✅ Found valid digest from manifest: $manifestDigest"
                  echo "IMAGE_DIGEST=$manifestDigest" >> $env:GITHUB_OUTPUT
                } else {
                  Write-Host "❌ Could not extract digest from manifest"
                }
              }
            } catch {
              Write-Host "❌ Error extracting digest: $_"
            }
            
            # Final check if we have a digest
            if (-not (Test-Path env:GITHUB_OUTPUT) -or -not (Get-Content $env:GITHUB_OUTPUT | Select-String "IMAGE_DIGEST=")) {
              Write-Host "⚠️ Could not extract a valid digest, using a placeholder format"
              # Create a normalized imageName output for later use
              echo "IMAGE_NAME=$imageName" >> $env:GITHUB_OUTPUT
              
              # Use fallback for attestation - empty digest will cause the attestation step to be skipped
              echo "IMAGE_DIGEST=" >> $env:GITHUB_OUTPUT
              echo "ATTESTATION_POSSIBLE=false" >> $env:GITHUB_OUTPUT
            } else {
              # Create a normalized imageName output for later use
              echo "IMAGE_NAME=$imageName" >> $env:GITHUB_OUTPUT
              echo "ATTESTATION_POSSIBLE=true" >> $env:GITHUB_OUTPUT
            }
          }
      
      - name: Verify digest for attestation
        shell: pwsh
        run: |
          $digest = "${{ steps.digest.outputs.IMAGE_DIGEST }}"
          $imageName = "${{ steps.digest.outputs.IMAGE_NAME }}"
          $attestPossible = "${{ steps.digest.outputs.ATTESTATION_POSSIBLE }}"
          
          Write-Host "Image name: $imageName"
          Write-Host "Image digest: $digest"
          Write-Host "Attestation possible: $attestPossible"
          
          # Verify the digest is in the correct format
          if ($digest -and $digest -match '^sha256:[a-f0-9]{64}$') {
            Write-Host "✅ Digest is in correct format for attestation"
          } else {
            Write-Host "❌ Digest is not in correct format or is missing"
          }
      
      # Only run attestation if we have confirmed we have a properly formatted digest
      - name: Generate artifact attestation
        id: attestation
        if: steps.digest.outputs.ATTESTATION_POSSIBLE == 'true' && steps.digest.outputs.IMAGE_DIGEST != ''
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ steps.digest.outputs.IMAGE_NAME }}
          subject-digest: ${{ steps.digest.outputs.IMAGE_DIGEST }}
          push-to-registry: true
        continue-on-error: true
      
      # Fallback manual attestation if the standard one fails
      - name: Attestation status
        shell: pwsh
        run: |
          $attestSuccess = "${{ steps.attestation.outcome }}" -eq "success"
          $imageName = "${{ steps.digest.outputs.IMAGE_NAME }}"
          $digest = "${{ steps.digest.outputs.IMAGE_DIGEST }}"
          
          if ($attestSuccess) {
            Write-Host "✅ Attestation generated successfully for $imageName@$digest"
          } else {
            Write-Host "⚠️ Standard attestation failed or was skipped"
            Write-Host "ℹ️ Image was published successfully to: $imageName"
            
            if ($digest) {
              Write-Host "ℹ️ Image digest: $digest"
            } else {
              Write-Host "⚠️ No digest available for this image"
            }
          }
          
          # Always show deployment success message
          Write-Host "✅ Deployment completed - image available at $imageName"
      
      # Enhanced debug step to check the build-and-push outputs
      - name: Check outputs
        shell: pwsh
        run: |
          Write-Host "Available outputs from build-and-push:"
          Write-Host "Digest: ${{ steps.build-and-push.outputs.digest }}"
          Write-Host "Metadata: ${{ steps.build-and-push.outputs.metadata }}"
          Write-Host "ImageID: ${{ steps.build-and-push.outputs.imageID }}"
          Write-Host "All outputs: ${{ toJSON(steps.build-and-push.outputs) }}"
      
      # Improved image details extraction
      - name: Store image details
        id: image-details
        shell: pwsh
        run: |
          # Format image name correctly
          $imageName = "${{ env.REGISTRY }}/${{ github.repository }}".ToLower()
          echo "IMAGE_NAME=$imageName" >> $env:GITHUB_OUTPUT
          Write-Host "Image Name: $imageName"
          
          # Try to get digest from build output first
          $digest = "${{ steps.build-and-push.outputs.digest }}"
          
          if ($digest) {
            Write-Host "Found digest from build output: $digest"
            echo "IMAGE_DIGEST=$digest" >> $env:GITHUB_OUTPUT
          } else {
            Write-Host "No digest in build output, attempting to get from Docker"
            # Get latest image
            $latestTag = "$imageName`:latest"
            docker pull $latestTag
            
            # Get full repo digest (includes repo name and digest)
            $repoDigest = $(docker inspect $latestTag --format='{{index .RepoDigests 0}}')
            Write-Host "Full repo digest: $repoDigest"
            
            if ($repoDigest) {
              # Extract just the sha256 part
              $digest = ($repoDigest -split '@')[1]
              if ($digest) {
                Write-Host "Extracted digest: $digest"
                echo "IMAGE_DIGEST=$digest" >> $env:GITHUB_OUTPUT
              } else {
                Write-Host "Failed to extract digest from repo digest: $repoDigest"
                echo "IMAGE_DIGEST=" >> $env:GITHUB_OUTPUT
              }
            } else {
              Write-Host "No repo digest found for image"
              echo "IMAGE_DIGEST=" >> $env:GITHUB_OUTPUT
            }
          }
      
      # Explicit validation step before attestation
      - name: Validate image details
        shell: pwsh
        run: |
          $imageName = "${{ steps.image-details.outputs.IMAGE_NAME }}"
          $digest = "${{ steps.image-details.outputs.IMAGE_DIGEST }}"
          
          Write-Host "Validation - Image Name: $imageName"
          Write-Host "Validation - Image Digest: $digest"
          
          if (-not $imageName) {
            Write-Host "::error::Image name is empty or undefined"
            exit 1
          }
          
          if (-not $digest) {
            Write-Host "::warning::Image digest is empty or undefined - attestation will be skipped"
          }
      
      # Only run attestation if digest is available and valid
      - name: Generate artifact attestation
        if: ${{ steps.image-details.outputs.IMAGE_DIGEST != '' }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ steps.image-details.outputs.IMAGE_NAME }}
          subject-digest: ${{ steps.image-details.outputs.IMAGE_DIGEST }}
          push-to-registry: true
      
      # Final confirmation message
      - name: Deployment status
        shell: pwsh
        run: |
          $imageName = "${{ steps.image-details.outputs.IMAGE_NAME }}"
          $digest = "${{ steps.image-details.outputs.IMAGE_DIGEST }}"
          
          if ($digest) {
            Write-Host "✅ Container successfully published to $imageName with digest $digest"
            Write-Host "✅ Attestation was generated for this container"
          } else {
            Write-Host "⚠️ Container published to $imageName but no digest was found"
            Write-Host "⚠️ Attestation was not generated for this container"